fos_user:
    db_driver: orm
    user_class: App\Entity\User\User
    firewall_name: main
    from_email:
        address: noreply@example.com
        sender_name: App

fos_oauth_server:
    db_driver: orm
    client_class:        App\Entity\OAuth\Client
    access_token_class:  App\Entity\OAuth\AccessToken
    refresh_token_class: App\Entity\OAuth\RefreshToken
    auth_code_class:     App\Entity\OAuth\AuthCode
    service:
        user_provider: fos_user.user_provider.username_email

fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    param_fetcher_listener: true
    body_listener: true
    body_converter:
        enabled: true
    view:
        view_response_listener: force
    serializer:
        serialize_null: true