security:

    encoders:
        App\Entity\User\User: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:   ^/(_(profiler|wdt)|css|images|js)/
            security:  false

        api_doc:
            pattern:   ^/api/doc
            security:  false

        api_oauth_token:
            pattern:   ^/api/v1/oauth/token
            security:  false

        api_registration:
            pattern:   ^/api/v1/registration
            security:  false

        api_restore_password:
            pattern:   ^/api/v1/restore-password
            security:  false

        api:
            pattern:   ^/api
            fos_oauth: true
            stateless: true
            security: false #remove if need secured api

    access_control:
        - { path: ^/api,                           role: IS_AUTHENTICATED_FULLY }